### PR TITLE
checkup doctor subcommand

### PR DESCRIPTION
**Pull request by scalvert**
[Rendered](https://github.com/checkupjs/rfcs/blob/checkup-doctor/text/0003-doctor.md)

### CODE REVIEW

**Comment by carakessler** [comment]
Is there a reason that the checks for doctor need to take a different format and use a different construct than tasks? Seems this may lead to some code duplication. 

How do you feel about adding an optional Doctor hook to existing tasks so we dont need to reinvent the wheel and create a whole new construct? I can see tasks that we want to use to gather metrics but ALSO fail doctor when given certain values? To me, doctor is just like a more urgent action (unless I am missing something). I think we can figure out a way to repurpose/add to actions/tasks to get this same functionality without adding these new constructs. Thoughts?

**Comment by scalvert** [comment]
Yep, we can totally repurpose. I want to get in there and start to implement before I make any decisions about whether we can reuse vs. build new. I think it'll be more clear once I start the work.

**Review by rwjblue — COMMENTED** [review]
Overall looks good to me, I had a few high level questions / concerns:

* We really need to be able to fetch a canonical configuration to validate against (instead of using the in-repo version). This could be as simple as fetching a config via HTTP or something, but may need more thought.
* Could you call out more details on the explicit `registerDoctorTask` choice? Naively it seems that you could use `registerTask` with an option (e.g. `registerTask(..., {doctor: true})`), but having doctor tasks be explicit here helps reduce "if doctor mode; do xyz" throughout normal tasks (and force sharing via shared utility functions and whatnot).

**Comment by scalvert** [comment]
@rwjblue Agree. I think fetching a config from an HTTP endpoint is what we've discussed as part of the general checkup functionality before. I think I'll implement it as part of that, as it's closely related.

Yes, will call out the latter, as it's precisely the reason why I want to do this. So we can bucket these tasks completely separate from regular tasks, and there won't need to be any conditional evaluation to determine whether to run or not.

**Pull request merged**
